//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbNexLumoEntities : DbContext
    {
        public DbNexLumoEntities()
            : base("name=DbNexLumoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbout { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAuthors> TblAuthors { get; set; }
        public virtual DbSet<TblBlogs> TblBlogs { get; set; }
        public virtual DbSet<TblCategories> TblCategories { get; set; }
        public virtual DbSet<TblContact> TblContact { get; set; }
        public virtual DbSet<TblFooter> TblFooter { get; set; }
        public virtual DbSet<TblHome> TblHome { get; set; }
        public virtual DbSet<TblServices> TblServices { get; set; }
        public virtual DbSet<TblSocialMedias> TblSocialMedias { get; set; }
        public virtual DbSet<TblTeams> TblTeams { get; set; }
        public virtual DbSet<TblTeamMembers> TblTeamMembers { get; set; }
    }
}
