//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblServices
    {
        public int id { get; set; }
        public string serviceimg { get; set; }
        public string serviceName { get; set; }
        public string serviceDescription { get; set; }
        public string serviceDescription2 { get; set; }
        public Nullable<int> categoryid { get; set; }
    }
}
