//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAuthors
    {
        public int id { get; set; }
        public string authorName { get; set; }
        public string authorimg { get; set; }
        public string authorTitle { get; set; }
        public Nullable<int> blogid { get; set; }
    }
}
