//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlogs
    {
        public int id { get; set; }
        public string blogHeader { get; set; }
        public string blogSlogan { get; set; }
        public string blogimg { get; set; }
        public string blogPost { get; set; }
        public string blogForeword { get; set; }
        public Nullable<System.DateTime> blogDate { get; set; }
        public Nullable<byte> blogHighlights { get; set; }
        public Nullable<int> authorid { get; set; }
        public string authorName { get; set; }
        public string authorMission { get; set; }
        public string authorimg { get; set; }
    }
}
