//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHome
    {
        public int id { get; set; }
        public string title { get; set; }
        public string slogan { get; set; }
        public string applicationTitle { get; set; }
        public string applicationName { get; set; }
        public string applicationPhone { get; set; }
        public string mailAddress { get; set; }
    }
}
