//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifena.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTeamMembers
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string mission { get; set; }
        public string website { get; set; }
        public string img { get; set; }
        public string socialMediaicon1 { get; set; }
        public string socialMediaicon2 { get; set; }
        public string socialMediaicon3 { get; set; }
        public string socialMediaLink1 { get; set; }
        public string socialMediaLink2 { get; set; }
        public string socialMediaLink3 { get; set; }
    }
}
